spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: uqi
    password: Deneme123..
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://uqi123.mysql.database.azure.com:3306/obss?useSSL=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true